# Generated by Django 5.1.1 on 2024-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
                ('model', models.CharField(max_length=150, verbose_name='Modelo')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bus/%Y/%m/%d')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'bus',
                'verbose_name_plural': 'buses',
                'db_table': 'Buses',
                'ordering': ['id'],
            },
        ),
    ]
