# Generated by Django 5.1.2 on 2024-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibus', '0003_role_date_creation_role_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('ci', models.CharField(max_length=10, unique=True, verbose_name='Cédula de Identidad')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
