# Generated by Django 5.1.2 on 2024-11-04 20:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibus', '0003_remove_category_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.AddField(
            model_name='client',
            name='ci',
            field=models.CharField(default='N/A', max_length=10, unique=True, verbose_name='Cédula de Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='Clientes',
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Peso')),
                ('declare_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor declarado')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo de envío')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to='calibus.client')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to='calibus.client')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'db_table': 'Encomiendas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto')),
                ('parc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibus.parcel')),
            ],
            options={
                'verbose_name': 'Detalle de Recibo',
                'verbose_name_plural': 'Detalles de Recibos',
                'db_table': 'DetallesRecibos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('origin', models.CharField(max_length=100, unique=True, verbose_name='Origen')),
                ('destination', models.CharField(blank=True, max_length=500, null=True, verbose_name='Destino')),
                ('estimated_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo estimado')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'Rutas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de salida')),
                ('arrival', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de llegada')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('rou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibus.route', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'Viajes',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
