# Generated by Django 5.1.2 on 2025-02-20 23:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0005_alter_route_origin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parcel",
            old_name="declare_value",
            new_name="declared_value",
        ),
        migrations.AddField(
            model_name="parcel",
            name="date_joined",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="parcel",
            name="travelID",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="calibus.travel",
            ),
            preserve_default=False,
        ),
    ]
