# Generated by Django 5.1.2 on 2025-03-11 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0006_rename_declare_value_parcel_declared_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=10, verbose_name="Placa"),
                ),
                (
                    "chassis_number",
                    models.CharField(max_length=20, verbose_name="Número de chasis"),
                ),
                (
                    "engine_number",
                    models.CharField(max_length=20, verbose_name="Número de motor"),
                ),
                ("model", models.CharField(max_length=30, verbose_name="Modelo")),
                ("color", models.CharField(max_length=20, verbose_name="Color")),
                ("brand", models.CharField(max_length=30, verbose_name="Marca")),
                ("capacity", models.PositiveIntegerField(verbose_name="Capacidad")),
                ("year", models.PositiveIntegerField(verbose_name="Año")),
                ("status", models.BooleanField(default=True, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Buses",
                "db_table": "Buses",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="nationality",
            field=models.CharField(
                default=None, max_length=20, verbose_name="Nacionalidad"
            ),
            preserve_default=False,
        ),
    ]
