# Generated by Django 5.1.2 on 2025-03-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0008_alter_client_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nationality",
            field=models.CharField(
                default="Desconocido", max_length=20, verbose_name="Nacionalidad"
            ),
        ),
    ]
