# Generated by Django 5.1.2 on 2025-03-13 23:50

import core.calibus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0010_rename_rou_travel_routeid_travel_busid"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel",
            name="departure_time",
            field=models.TimeField(
                default=core.calibus.models.current_time, verbose_name="Hora de salida"
            ),
        ),
    ]
