# Generated by Django 5.1.2 on 2025-05-02 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0011_travel_departure_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="declared_value",
        ),
        migrations.RemoveField(
            model_name="parcel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="parcel",
            name="shipping_cost",
        ),
        migrations.RemoveField(
            model_name="parcel",
            name="weight",
        ),
        migrations.AlterField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_transit", "En tránsito"),
                    ("ready_for_pickup", "Listo para recoger"),
                    ("delivered", "Entregado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=9, verbose_name="Peso"
                    ),
                ),
                (
                    "declared_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Valor declarado",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Costo de envío",
                    ),
                ),
                (
                    "parcelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calibus.parcel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Encomienda",
                "verbose_name_plural": "Deatlle de Encomiendas",
                "db_table": "Detalle de Encomiendas",
                "ordering": ["id"],
            },
        ),
    ]
