# Generated by Django 5.1.2 on 2025-05-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0012_remove_parcel_declared_value_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShipmentItem",
            new_name="ParcelItem",
        ),
        migrations.AlterModelTable(
            name="parcelitem",
            table="DetallesEncomiendas",
        ),
    ]
