# Generated by Django 5.1.2 on 2025-05-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0013_rename_shipmentitem_parcelitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Total Precio de Envío",
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pendiente"),
                    ("in_transit", "En tránsito"),
                    ("ready_for_pickup", "Listo para recoger"),
                    ("delivered", "Entregado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Estado",
            ),
        ),
    ]
