# Generated by Django 5.1.2 on 2025-05-05 04:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0014_parcel_total_alter_parcel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Fecha de registro"
            ),
        ),
        migrations.CreateModel(
            name="Remittance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Monto",
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Comisión",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        default=datetime.datetime.now,
                        verbose_name="Fecha de transacción",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de entrega",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "receiverID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_remittances",
                        to="calibus.client",
                    ),
                ),
                (
                    "senderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_remittances",
                        to="calibus.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giro",
                "verbose_name_plural": "Giros",
                "db_table": "Giros",
                "ordering": ["id"],
            },
        ),
    ]
