# Generated by Django 5.1.2 on 2025-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0015_alter_parcel_date_joined_remittance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remittance",
            name="transfer_fee",
        ),
        migrations.AddField(
            model_name="remittance",
            name="comission_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=9,
                verbose_name="Monto de la Comisión",
            ),
        ),
        migrations.AddField(
            model_name="remittance",
            name="comission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=9,
                verbose_name="Procentaje de Comisión",
            ),
        ),
    ]
