# Generated by Django 5.1.2 on 2025-05-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0016_remove_remittance_transfer_fee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remittance",
            old_name="comission_amount",
            new_name="commission_amount",
        ),
        migrations.RenameField(
            model_name="remittance",
            old_name="comission_percentage",
            new_name="commission_percentage",
        ),
    ]
