# Generated by Django 5.1.2 on 2025-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calibus",
            "0017_rename_comission_amount_remittance_commission_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="remittance",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Monto total"
            ),
        ),
        migrations.AlterField(
            model_name="remittance",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=9,
                verbose_name="Monto a enviar",
            ),
        ),
    ]
