# Generated by Django 5.1.2 on 2025-05-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0018_remittance_total_amount_alter_remittance_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remittance",
            old_name="amount",
            new_name="amount_to_send",
        ),
    ]
