# Generated by Django 5.1.2 on 2025-05-23 23:02

import core.calibus.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0019_rename_amount_remittance_amount_to_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remittance",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=9,
                verbose_name="Potcentaje de Comisión",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha de compra"
                    ),
                ),
                (
                    "purchase_time",
                    models.TimeField(
                        default=core.calibus.models.current_time,
                        verbose_name="Hora de compra",
                    ),
                ),
                ("ticket_type", models.CharField()),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio total",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "clientID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calibus.client"
                    ),
                ),
                (
                    "travelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calibus.travel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasaje",
                "verbose_name_plural": "Pasajes",
                "db_table": "Pasajes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TicketDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.IntegerField(default=0, verbose_name="Número de asiento"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "passengerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calibus.client",
                        verbose_name="Pasajero",
                    ),
                ),
                (
                    "ticketID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calibus.ticket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pasaje",
                "verbose_name_plural": "Detalle de Pasajes",
                "db_table": "DetallesPasajes",
                "ordering": ["id"],
            },
        ),
    ]
