# Generated by Django 5.1.2 on 2025-05-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0020_alter_remittance_commission_percentage_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="status",
            field=models.CharField(
                choices=[("active", "Activo"), ("inactive", "Inactivo")],
                default="active",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
    ]
