# Generated by Django 5.1.2 on 2025-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0021_alter_travel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("reservado", "Reservado"),
                    ("vendido", "Vendido"),
                    ("libre", "Libre"),
                ],
                default="reservado",
                max_length=20,
                verbose_name="Tipo de pasaje",
            ),
        ),
    ]
