# Generated by Django 5.1.2 on 2025-06-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0022_alter_ticket_ticket_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="purchase_time",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("reservado", "Reservado"),
                    ("vendido", "Vendido"),
                    ("libre", "Libre"),
                ],
                default="libre",
                max_length=20,
                verbose_name="Tipo de pasaje",
            ),
        ),
    ]
