# Generated by Django 5.1.2 on 2025-06-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0024_alter_ticketdetail_passengerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCashBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Ingresos"
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Egresos"
                    ),
                ),
                (
                    "final_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Final"
                    ),
                ),
                (
                    "cashbox_type",
                    models.CharField(
                        choices=[
                            ("shift_change", "Cambio de turno"),
                            ("cash_closing", "Cierre de caja"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de arqueo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja Diaria",
                "verbose_name_plural": "Cajas Diarias",
                "db_table": "CajaDiaria",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Egreso")],
                        max_length=10,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("qr", "Pago con QR"), ("cash", "Pago en efectivo")],
                        max_length=10,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                ("time", models.TimeField(auto_now_add=True, verbose_name="Hora")),
                (
                    "ticket_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID del Ticket"
                    ),
                ),
                (
                    "parcel_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID de la Encomienda"
                    ),
                ),
                (
                    "cashboxID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calibus.dailycashbox",
                        verbose_name="Caja Diaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "db_table": "MovimientosCaja",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(
            name="ReceiptDetail",
        ),
    ]
