# Generated by Django 5.1.2 on 2025-06-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibus", "0025_dailycashbox_cashmovement_delete_receiptdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycashbox",
            name="status",
            field=models.CharField(
                choices=[("open", "Abierto"), ("closed", "Cerrado")],
                default="open",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
    ]
