# Generated by Django 5.1.2 on 2024-10-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Cédula Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=10, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
