# Generated by Django 5.1.2 on 2025-07-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_ci_user_phone_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
